// ─── FOOD DATA MODEL ──────────────────────────────────────────
// Shared tips to avoid repeating the same text hundreds of times.
const String breadTip =
    'White bread and rye are the safest. Avoid whole wheat products and bran muffins which are higher in oxalates.';

const String dairyTip =
    'Dairy is your best friend! The calcium in dairy binds oxalates in the gut, preventing absorption. Eat dairy with every meal.';

const String beansTip =
    'Lentils and kidney beans are the safest legumes. Avoid baked beans, refried beans, and plant-based burgers.';

const String vegetablesTip =
    'AVOID spinach entirely (547mg!). Safest veggies: lettuce, mushrooms, cauliflower, cabbage, corn, peas.';

const String fruitTip =
    'Most fruits are low oxalate. Avoid oranges and tangerines (high). Best choices: apples, peaches, watermelon, grapes.';

const String grainsTip =
    'White rice and barley are the best grains. Avoid buckwheat, bulgur, quinoa, and whole wheat pasta.';

const String nutsTip =
    'Avoid almonds, cashews, and peanuts entirely. Safest options: pistachios, coconut, flaxseed, and sunflower seeds.';

const String coldCerealTip =
    'Stick to low-oxalate cereals. Corn Flakes and Rice Krispies are the safest options. Avoid bran-heavy cereals.';

const String hotCerealTip =
    'Plain oatmeal (instant Quaker) is surprisingly zero oxalate! Avoid corn grits which are very high.';

const String snacksTip =
    'Popcorn and pretzels are the safest snacks. Avoid baked potato chips (19mg) and high-protein bars.';

const String soupsTip =
    'Avoid miso soup (58mg) entirely. Cream of mushroom and tomato soup are the safest choices.';

const String meatTip =
    'All plain meats are zero or near-zero oxalate. Grill, bake, or pan-fry freely. Avoid heavy spice rubs.';

const String fishTip =
    'All fish and seafood are extremely low or zero oxalate. Eat freely. A great daily protein source.';

const String poultryTip =
    'All plain chicken and turkey are zero or near-zero oxalate. A perfect protein staple for a low-oxalate diet.';

enum OxalateLevel { low, moderate, high, veryHigh }

class FoodItem {
  final String name;
  final String serving;
  final double oxalateMg;
  final OxalateLevel level;
  final String category;
  final String tip;

  const FoodItem({
    required this.name,
    required this.serving,
    required this.oxalateMg,
    required this.level,
    required this.category,
    required this.tip,
  });
}

// â”€â”€â”€ FOOD DATABASE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// â”€â”€â”€ HARVARD OXALATE DATABASE (431 foods) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Source: Harvard T.H. Chan School of Public Health, Nov. 2023
// Oxalate measurements by Dr. John Knight, University of Alabama School of Medicine

const List<FoodItem> foodDatabase = [
  FoodItem(name: '100% Natural Granola Oats Wheat & Honey', serving: '2/3 cup', oxalateMg: 13.0, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: '40% Bran Flakes', serving: '1 cup', oxalateMg: 42.7, level: OxalateLevel.high, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'All Bran Kelloggs', serving: '2/3 cup', oxalateMg: 34.6, level: OxalateLevel.high, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Basic 4', serving: '1 cup', oxalateMg: 11.2, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Cap\'N Crunch', serving: '1 cup', oxalateMg: 1.6, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Cheerios', serving: '1 1/2 cup', oxalateMg: 7.4, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Cheerios Multigrain', serving: '1 1/3 cup', oxalateMg: 5.1, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Cheerios Honey Nut', serving: '1 cup', oxalateMg: 6.6, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Krave Chocolate', serving: '1 cup', oxalateMg: 14.7, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Cinnamon Toast Crunch', serving: '1 cup', oxalateMg: 7.2, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Cocoa Pebbles', serving: '1 cup', oxalateMg: 8.8, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Cocoa Puffs', serving: '1 cup', oxalateMg: 6.4, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Corn Chex', serving: '1 1/4 cup', oxalateMg: 4.9, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Corn Flakes', serving: '1 1/2 cup', oxalateMg: 0.8, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Corn Pops', serving: '1 1/3 cup', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Cracklin Oat Bran', serving: '3/4 cup', oxalateMg: 11.6, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Crispix', serving: '1 1/3 cup', oxalateMg: 2.3, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Fiber One', serving: '2/3 cup', oxalateMg: 12.8, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Fiber One Honey Clusters', serving: '1 cup', oxalateMg: 12.6, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Froot Loops', serving: '1 1/3 cup', oxalateMg: 4.1, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Frosted Flakes', serving: '1 cup', oxalateMg: 1.0, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Frosted Miniwheats', serving: '25 biscuits', oxalateMg: 32.9, level: OxalateLevel.high, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Grape-Nuts', serving: '1/2 cup', oxalateMg: 13.7, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Great Grains Cranberry Almond Crunch', serving: '1 cup', oxalateMg: 28.2, level: OxalateLevel.high, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Great Grains Crunchy Pecan', serving: '3/4 cup', oxalateMg: 23.1, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Great Grains Raisin Date & Pecan', serving: '3/4 cup', oxalateMg: 18.6, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Honey Bunches Of Oats With Almonds', serving: '1 cup', oxalateMg: 7.1, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Honey Bunches Of Oats Honey Roasted', serving: '1 cup', oxalateMg: 4.0, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Kashi Autumn Wheat', serving: '32 biscuits', oxalateMg: 32.9, level: OxalateLevel.high, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Kashi Go', serving: '3/4 cup', oxalateMg: 10.7, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Kashi Heart To Heart', serving: '1 cup', oxalateMg: 6.7, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Lucky Charms', serving: '1 cup', oxalateMg: 5.5, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Oat Life', serving: '1 cup', oxalateMg: 4.0, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Oatmeal Crisp Crunchy Almonds', serving: '1 cup', oxalateMg: 26.1, level: OxalateLevel.high, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Oatmeal Squares', serving: '1 cup', oxalateMg: 12.0, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Puffed Rice', serving: '1 cup', oxalateMg: 1.8, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Puffed Wheat', serving: '1 cup', oxalateMg: 9.2, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Raisin Bran', serving: '1 cup', oxalateMg: 46.1, level: OxalateLevel.high, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Raisin Nut Bran', serving: '1 cup', oxalateMg: 44.8, level: OxalateLevel.high, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Reese\'S Puffs', serving: '1 cup', oxalateMg: 10.6, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Rice Chex', serving: '1 1/3 cup', oxalateMg: 3.5, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Rice Krispies', serving: '1 1/2 cup', oxalateMg: 3.1, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Shredded Wheat', serving: '1 1/3 cup', oxalateMg: 41.8, level: OxalateLevel.high, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Smart Start', serving: '1 1/4 cup', oxalateMg: 14.9, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Special K', serving: '1 1/4 cup', oxalateMg: 7.3, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Special K Red Berries', serving: '1 cup', oxalateMg: 8.2, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Total Whole Grain', serving: '1 cup', oxalateMg: 10.4, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Uncle Sam', serving: '3/4 cup', oxalateMg: 41.7, level: OxalateLevel.high, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Weetabix', serving: '3 biscuits', oxalateMg: 24.8, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Wheat Chex', serving: '1 cup', oxalateMg: 15.3, level: OxalateLevel.moderate, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Wheat Germ Toasted Plain', serving: '1 tbsp', oxalateMg: 1.4, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Wheaties', serving: '1 cup', oxalateMg: 9.4, level: OxalateLevel.low, category: 'Cold Cereal', tip: coldCerealTip),
  FoodItem(name: 'Corn Grits Cooked With Water', serving: '1 cup', oxalateMg: 45.2, level: OxalateLevel.high, category: 'Hot Cereal', tip: hotCerealTip),
  FoodItem(name: 'Cream Of Wheat Quick Cooked With Water', serving: '1 cup', oxalateMg: 17.7, level: OxalateLevel.moderate, category: 'Hot Cereal', tip: hotCerealTip),
  FoodItem(name: 'Oatmeal Quaker Instant Sweetened', serving: '2/3 cup', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Hot Cereal', tip: hotCerealTip),
  FoodItem(name: 'Oatmeal Quaker Multigrain Cooked With Water', serving: '1 cup', oxalateMg: 21.7, level: OxalateLevel.low, category: 'Hot Cereal', tip: hotCerealTip),
  FoodItem(name: 'Oats Regular Quick Instant Cooked With Water', serving: '1 cup', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Hot Cereal', tip: hotCerealTip),
  FoodItem(name: 'Beer Regular Light Hard Cider', serving: '12 oz', oxalateMg: 3.9, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Boost', serving: '8 oz', oxalateMg: 21.1, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Carbonated Beverage With Sugar Without Caffeine', serving: '12 oz', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Carnation Instant Breakfast Prepared', serving: '8 oz', oxalateMg: 7.3, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Coffee Drinks Cappuccino Latte Mocha Frappuccino', serving: '12 oz', oxalateMg: 13.0, level: OxalateLevel.moderate, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Coffee Brewed', serving: '8 oz', oxalateMg: 1.7, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Coffee Prepared Instant Decaf', serving: '8 oz', oxalateMg: 2.2, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Cola Caffeinated', serving: '12 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Diet Soda No Caffeine', serving: '12 oz', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Diet Soda With Caffeine', serving: '12 oz', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Energy Drink Red Bull', serving: '8.3 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Energy Drink Red Bull Sugar Free', serving: '8.3 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Ensure Nutritional Supplement', serving: '8 oz', oxalateMg: 2.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Ensure Plus Nutrition Shake', serving: '8 oz', oxalateMg: 12.3, level: OxalateLevel.moderate, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Fruit Smoothie', serving: '16 oz', oxalateMg: 9.3, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Gatorade Fruit Flavored', serving: '12 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Apple Unsweetened', serving: '7 oz', oxalateMg: 1.5, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Apricot', serving: '8 oz', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Carrot Canned', serving: '1 cup', oxalateMg: 28.3, level: OxalateLevel.high, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Citrus Fruit From Frozen Concentrate', serving: '12 oz', oxalateMg: 4.5, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Cranberry Cocktail', serving: '6 oz', oxalateMg: 1.7, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Grape Unsweetened', serving: '6 oz', oxalateMg: 2.4, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Grapefruit', serving: '6 oz', oxalateMg: 2.2, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Lemon Raw', serving: '1 tbsp', oxalateMg: 0.9, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Mango', serving: '1 cup', oxalateMg: 1.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Orange With Calcium', serving: '6 oz', oxalateMg: 1.1, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Orange Unsweetened Frozen', serving: '6 oz', oxalateMg: 1.1, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Pineapple Canned Unsweetened', serving: '6 oz', oxalateMg: 1.9, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Pomegranate', serving: '6 oz', oxalateMg: 1.3, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Tomato Canned', serving: '6 oz', oxalateMg: 10.7, level: OxalateLevel.moderate, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Juice Vegetable Canned', serving: '6 oz', oxalateMg: 13.7, level: OxalateLevel.moderate, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Lemonade Frozen From Concentrate', serving: '12 oz', oxalateMg: 22.3, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Lemonade Low Calorie', serving: '12 oz', oxalateMg: 1.4, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Papaya Canned Nectar', serving: '1 cup', oxalateMg: 0.8, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Powerade Zero', serving: '12 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Slim Fast', serving: '11 oz', oxalateMg: 36.7, level: OxalateLevel.high, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Tea Brewed', serving: '8 oz', oxalateMg: 6.4, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Tea Diet Iced Ready To Drink', serving: '12 oz', oxalateMg: 9.6, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Tea Instant Lemon Flavored', serving: '4.5 tsp dry', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Tea Unsweetened Green', serving: '1 cup', oxalateMg: 6.4, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Vitamin Water Sugared', serving: '8 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Vitamin Water Sugar-Free', serving: '8 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Water Tap', serving: '8 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'White & Dark Spirits Hard Seltzer Mixed Cocktail', serving: '1.5 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Wine Red', serving: '5 oz', oxalateMg: 1.2, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Wine White', serving: '5 oz', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Beverages', tip: 'Stay well hydrated â€” aim for 80+ oz of water daily. Coffee and OJ are safe. Avoid Slim Fast and carrot juice.'),
  FoodItem(name: 'Beans Baked Canned Vegetarian', serving: '1/2 cup', oxalateMg: 57.5, level: OxalateLevel.veryHigh, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Beans Black Boiled', serving: '1/2 cup', oxalateMg: 10.5, level: OxalateLevel.moderate, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Beans Navy Canned', serving: '1/2 cup', oxalateMg: 96.3, level: OxalateLevel.veryHigh, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Beans Red Kidney Boiled', serving: '1/2 cup', oxalateMg: 9.9, level: OxalateLevel.low, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Beans Refried Canned', serving: '1/2 cup', oxalateMg: 59.6, level: OxalateLevel.veryHigh, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Burger Plant-Based', serving: '1 patty', oxalateMg: 57.9, level: OxalateLevel.veryHigh, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Burger Soy', serving: '3.5 oz', oxalateMg: 11.9, level: OxalateLevel.moderate, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Burger Vegetable', serving: 'one', oxalateMg: 5.0, level: OxalateLevel.low, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Hummus Commercial', serving: '1/4 cup', oxalateMg: 39.1, level: OxalateLevel.high, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Lentils Boiled', serving: '1/2 cup', oxalateMg: 2.4, level: OxalateLevel.low, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Tofu Soft', serving: '3.5 oz', oxalateMg: 10.6, level: OxalateLevel.moderate, category: 'Beans And Lentils', tip: beansTip),
  FoodItem(name: 'Biscuit', serving: 'one', oxalateMg: 13.5, level: OxalateLevel.moderate, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Bread Multigrain Whole Grain', serving: '1 slice', oxalateMg: 18.0, level: OxalateLevel.moderate, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Bread Oat Whole', serving: '1 slice', oxalateMg: 6.4, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Bread Rye', serving: '1 slice', oxalateMg: 6.3, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Bread Wheat', serving: '1 slice', oxalateMg: 3.2, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Bread White', serving: '1 slice', oxalateMg: 4.4, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Bread Whole Wheat', serving: '1 slice', oxalateMg: 13.6, level: OxalateLevel.moderate, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Brownie Home-Made', serving: 'one', oxalateMg: 31.0, level: OxalateLevel.high, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Brownie Ready-To-Eat', serving: 'one', oxalateMg: 33.9, level: OxalateLevel.high, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Cinnamon Bun Honey Bun', serving: '1 roll', oxalateMg: 7.2, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Cake Commercial Yellow With Chocolate Frosting', serving: '1 slice', oxalateMg: 19.3, level: OxalateLevel.moderate, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Cake Home-Baked And Commercial', serving: '1 slice', oxalateMg: 11.9, level: OxalateLevel.moderate, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Cookie Chocolate Chip', serving: '1 cookie', oxalateMg: 6.0, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Cookie Commercial', serving: '1 cookie', oxalateMg: 7.0, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Cornbread Or Corn Muffin', serving: '1 piece', oxalateMg: 3.7, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Cracker Multigrain', serving: '5-6 crackers', oxalateMg: 5.5, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Cracker Regular Refined Grain', serving: '5-6 crackers', oxalateMg: 5.1, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Crackers Whole Wheat', serving: '5-6 crackers', oxalateMg: 15.0, level: OxalateLevel.moderate, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Croissant', serving: 'one', oxalateMg: 7.6, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Danish Cinnamon Roll Or Fruit', serving: 'one', oxalateMg: 2.6, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Donut Cake Or Yeast', serving: 'one', oxalateMg: 4.4, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'French Toast Homemade With 2% Milk', serving: '2 slices', oxalateMg: 11.6, level: OxalateLevel.moderate, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Muffin Blueberry', serving: 'one', oxalateMg: 7.0, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Muffin Bran', serving: 'one', oxalateMg: 9.0, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Muffin English Wheat', serving: 'one', oxalateMg: 8.7, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Muffin English Mixed Grain', serving: 'one', oxalateMg: 11.2, level: OxalateLevel.moderate, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Muffin English Plain Enriched', serving: 'one', oxalateMg: 7.3, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Muffin English Whole Wheat', serving: 'one', oxalateMg: 28.1, level: OxalateLevel.high, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Pancakes & Waffles', serving: '2 small', oxalateMg: 9.7, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Pie Apple Commercial', serving: '1 slice', oxalateMg: 4.6, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Roll Reduced Fat Sweet', serving: 'one', oxalateMg: 13.5, level: OxalateLevel.moderate, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Snack Bar Granola Nutrigrain', serving: 'one', oxalateMg: 6.1, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Snack Cake Creme-Filled Sponge', serving: 'one', oxalateMg: 3.6, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Tortillas Corn', serving: 'two', oxalateMg: 10.0, level: OxalateLevel.moderate, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Tortillas Flour', serving: 'two', oxalateMg: 9.0, level: OxalateLevel.low, category: 'Breads And Bakery', tip: breadTip),
  FoodItem(name: 'Candies Milk Chocolate', serving: '1.5 oz', oxalateMg: 7.0, level: OxalateLevel.low, category: 'Candy', tip: 'Avoid dark chocolate entirely (67mg!). Non-chocolate candies are safe. Limit regular candy bars.'),
  FoodItem(name: 'Candies Non-Chocolate', serving: '1 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Candy', tip: 'Avoid dark chocolate entirely (67mg!). Non-chocolate candies are safe. Limit regular candy bars.'),
  FoodItem(name: 'Candy Bar', serving: '2 oz', oxalateMg: 35.4, level: OxalateLevel.high, category: 'Candy', tip: 'Avoid dark chocolate entirely (67mg!). Non-chocolate candies are safe. Limit regular candy bars.'),
  FoodItem(name: 'Chocolate Dark Bar', serving: '1.5 oz', oxalateMg: 67.7, level: OxalateLevel.veryHigh, category: 'Candy', tip: 'Avoid dark chocolate entirely (67mg!). Non-chocolate candies are safe. Limit regular candy bars.'),
  FoodItem(name: 'Catsup Ketchup', serving: '1 tbsp', oxalateMg: 1.5, level: OxalateLevel.low, category: 'Condiments', tip: 'Most condiments are very low oxalate. Ketchup, mustard, and BBQ sauce are all safe in normal amounts.'),
  FoodItem(name: 'Mustard Yellow', serving: '1 tsp', oxalateMg: 0.6, level: OxalateLevel.low, category: 'Condiments', tip: 'Most condiments are very low oxalate. Ketchup, mustard, and BBQ sauce are all safe in normal amounts.'),
  FoodItem(name: 'Sauce Barbecue', serving: '2 tbsp', oxalateMg: 2.3, level: OxalateLevel.low, category: 'Condiments', tip: 'Most condiments are very low oxalate. Ketchup, mustard, and BBQ sauce are all safe in normal amounts.'),
  FoodItem(name: 'Sauce Soy', serving: '1 tbsp', oxalateMg: 2.9, level: OxalateLevel.low, category: 'Condiments', tip: 'Most condiments are very low oxalate. Ketchup, mustard, and BBQ sauce are all safe in normal amounts.'),
  FoodItem(name: 'Butter Salted', serving: '1 tsp', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Buttermilk Lowfat', serving: '1 cup', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese American Pasteurized', serving: '1 oz', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese American Pasteurized Nonfat', serving: '1 slice', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese Cheddar', serving: '1 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese Cheddar/Colby Low Fat', serving: '1 oz', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese Cottage', serving: '1/2 cup', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese Cottage 1% Lowfat', serving: '1/2 cup', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese Cottage Nonfat', serving: '1/2 cup', oxalateMg: 0.8, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese Cream', serving: '1 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese Cream Fat Free', serving: '1 oz', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese Mozzarella Part Skim', serving: '1 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese Mozzarella Whole Milk', serving: '1 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cheese Neufchatel Lowfat Cream Cheese', serving: '1 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Coffeemate Powdered And Liquid', serving: '1 tbsp', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cream Fluid Light', serving: '1 tbsp', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Cream Sour', serving: '1 tbsp', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Ice Cream Light Vanilla', serving: '1 cup', oxalateMg: 0.6, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Ice Cream Vanilla', serving: '1 cup', oxalateMg: 1.0, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Milk 1%', serving: '8 oz', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Milk 2%', serving: '8 oz', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Milk Skim', serving: '8 oz', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Milk Whole', serving: '8 oz', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Sherbet Orange', serving: '1 cup', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Whipped Topping', serving: '2 tbsp', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Frozen Low Fat', serving: '1 cup', oxalateMg: 0.9, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Greek Chobani', serving: '5.3 oz', oxalateMg: 0.9, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Greek Frozen', serving: '1 bar', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Greek Fruit Whole Milk', serving: '6 oz', oxalateMg: 1.0, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Greek Light', serving: '5.3 oz', oxalateMg: 0.6, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Greek Plain Nonfat/Lowfat', serving: '5.3 oz', oxalateMg: 0.6, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Greek Plain Whole Milk', serving: '6 oz', oxalateMg: 0.8, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Lowfat Fruited', serving: '6 oz', oxalateMg: 1.2, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Nonfat Light Fruit', serving: '6 oz', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Nonfat With Fruit', serving: '6 oz', oxalateMg: 0.8, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Plain Lowfat', serving: '6 oz', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Plain Whole Milk', serving: '6 oz', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Yogurt Whole Fruit', serving: '6 oz', oxalateMg: 0.8, level: OxalateLevel.low, category: 'Dairy', tip: dairyTip),
  FoodItem(name: 'Almond Milk Sweetened Or Unsweetened', serving: '8 oz', oxalateMg: 27.1, level: OxalateLevel.high, category: 'Plant-Based Milk', tip: 'Avoid almond milk (27mg). Use regular dairy milk or plain plant-based milks (not soy or almond).'),
  FoodItem(name: 'Plant-Based Milk Excludes Soy & Almond', serving: '1 cup', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Plant-Based Milk', tip: 'Avoid almond milk (27mg). Use regular dairy milk or plain plant-based milks (not soy or almond).'),
  FoodItem(name: 'Soymilk Fortified', serving: '8 oz', oxalateMg: 9.6, level: OxalateLevel.low, category: 'Plant-Based Milk', tip: 'Avoid almond milk (27mg). Use regular dairy milk or plain plant-based milks (not soy or almond).'),
  FoodItem(name: 'Whey Powder High Protein Drink', serving: '1 scoop', oxalateMg: 1.5, level: OxalateLevel.low, category: 'Plant-Based Milk', tip: 'Avoid almond milk (27mg). Use regular dairy milk or plain plant-based milks (not soy or almond).'),
  FoodItem(name: 'Egg Beaters', serving: '1/4 cup', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Eggs', tip: 'All eggs are zero oxalate â€” a perfect protein source for every meal.'),
  FoodItem(name: 'Egg Raw Whole', serving: 'one', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Eggs', tip: 'All eggs are zero oxalate â€” a perfect protein source for every meal.'),
  FoodItem(name: 'Egg Yolk Raw Fresh', serving: 'one', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Eggs', tip: 'All eggs are zero oxalate â€” a perfect protein source for every meal.'),
  FoodItem(name: 'Eggs Omega 3 Supplemented', serving: 'one', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Eggs', tip: 'All eggs are zero oxalate â€” a perfect protein source for every meal.'),
  FoodItem(name: 'Apples Raw With Skin', serving: 'one', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Apples Raw Without Skin', serving: 'one', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Apples Sulfured Dried', serving: '1/4 cup', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Apricots Raw', serving: '1 fruit', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Apricots Sulfured Dried', serving: '5 halves', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Avocado', serving: '1/2 fruit', oxalateMg: 9.5, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Bananas Raw', serving: 'one', oxalateMg: 10.3, level: OxalateLevel.moderate, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Blueberries', serving: '1/2 cup', oxalateMg: 18.5, level: OxalateLevel.moderate, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Cantaloupe', serving: '1/4 melon', oxalateMg: 1.4, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Cherries Sweet Raw', serving: '1/2 cup', oxalateMg: 1.7, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Cranberries Dried Sweetened', serving: '1/4 cup', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Cranberries Raw', serving: '1 cup', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Cranberry Sauce Canned Sweetened', serving: '1/8 cup', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Dates', serving: '5 dates', oxalateMg: 25.5, level: OxalateLevel.high, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Figs Dried', serving: 'one', oxalateMg: 5.0, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Figs Raw', serving: 'one', oxalateMg: 9.3, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Grapefruit Raw', serving: '1/2 medium', oxalateMg: 13.2, level: OxalateLevel.moderate, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Grapes Red Or Green Seedless', serving: '1/2 cup', oxalateMg: 1.2, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Lemons Raw Without Peel', serving: '1/4 lemon', oxalateMg: 1.2, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Limes Raw', serving: '1/8 lime', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Mangos Raw', serving: '1/2 fruit', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Mixed Dried Fruit Prunes Apricots Pears', serving: '1/4 cup', oxalateMg: 6.1, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Nectarines Raw', serving: 'one', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Olives Canned Ripe', serving: '3 medium', oxalateMg: 5.0, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Oranges Raw', serving: 'one', oxalateMg: 23.3, level: OxalateLevel.moderate, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Papayas Raw', serving: '1/2 medium', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Peaches Canned In Heavy Syrup', serving: '1/2 cup', oxalateMg: 0.9, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Peaches Canned Juice Packed', serving: '1/2 cup', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Peaches Raw', serving: 'one', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Pears Raw', serving: 'one', oxalateMg: 1.8, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Pineapple Canned In Heavy Syrup', serving: '1/2 cup', oxalateMg: 11.9, level: OxalateLevel.moderate, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Pineapple Dried', serving: '1 ring', oxalateMg: 7.9, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Pineapple Raw', serving: '1/2 cup', oxalateMg: 5.2, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Plums Dried Prunes', serving: '1/4 cup', oxalateMg: 17.8, level: OxalateLevel.moderate, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Plums Raw', serving: 'one', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Pomegranates Raw', serving: '1/2 cup', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Prunes Canned In Heavy Syrup', serving: '1/2 cup', oxalateMg: 0.6, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Raisins', serving: '1 oz', oxalateMg: 2.5, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Raspberries Raw', serving: '1/2 cup', oxalateMg: 2.5, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Strawberries Raw', serving: '1/2 cup', oxalateMg: 1.2, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Tangerines Raw', serving: 'one', oxalateMg: 15.7, level: OxalateLevel.moderate, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Watermelon', serving: '1 slice', oxalateMg: 0.6, level: OxalateLevel.low, category: 'Fruit', tip: fruitTip),
  FoodItem(name: 'Bluefish Dry Heat Cooked', serving: '4 oz', oxalateMg: 1.2, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Catfish Farmed Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Clam Cooked Moist Heat', serving: '3 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Clams Raw', serving: '1 pint', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Cod Atlantic Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Cod Pacific Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Fish Sticks Frozen', serving: '3 oz', oxalateMg: 5.2, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Flounder & Sole Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Haddock Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Halibut Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Herring Atlantic Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Mackerel Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Oysters Farmed Dry Heat Cooked', serving: '3 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Oysters Wild Raw', serving: '6 medium', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Pollock Atlantic Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Salmon Atlantic Farmed Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Salmon Chum Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Salmon Pink Canned With Bones', serving: '4 oz', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Salmon Pink Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Salmon Sockeye Canned Drained With Bones', serving: '4 oz', oxalateMg: 1.6, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Salmon Sockeye Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Sardines Atlantic Oil Canned Drained', serving: '4 oz', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Sardines Pacific Tomato Sauce Canned', serving: '4 oz', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Shrimp Moist Heat Cooked', serving: '3 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Swordfish Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Tilapia Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Tuna Light In Oil', serving: '3.5 oz', oxalateMg: 2.8, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Tuna Light Canned In Water Drained', serving: '3.5 oz', oxalateMg: 1.5, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Tuna White Oil Canned Drained', serving: '3.5 oz', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Tuna White Water Canned Drained', serving: '3.5 oz', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Tuna Yellowfin Dry Heat Cooked', serving: '4 oz', oxalateMg: 0.6, level: OxalateLevel.low, category: 'Fish', tip: fishTip),
  FoodItem(name: 'Bacon Broiled Pan-Fried Or Roasted', serving: '2 slices', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Beef Hot Dog', serving: 'one', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Beef Liver Pan Fried', serving: '4 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Beef Patty Broiled 80% Lean', serving: '3 oz', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Beef Patty Broiled 85% Lean', serving: '3 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Beef Patty Broiled 93% Lean', serving: '3 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Beef Frankfurter Low-Fat', serving: 'one', oxalateMg: 0.6, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Beef Top Market Cuts', serving: '5 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Bologna Beef And Pork', serving: '2 slices', oxalateMg: 0.8, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Ham Canned', serving: '5 oz', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Pork Loin/Chops Broiled', serving: '5 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Sausage Cooked Pork & Beef', serving: '2 oz', oxalateMg: 1.8, level: OxalateLevel.low, category: 'Meat', tip: meatTip),
  FoodItem(name: 'Macaroni And Cheese', serving: '1 cup', oxalateMg: 15.3, level: OxalateLevel.moderate, category: 'Mixed Dishes', tip: 'Watch out for meat lasagna and mac & cheese. Pizza in moderation is fine. Avoid high-oxalate pasta dishes.'),
  FoodItem(name: 'Meat Lasagna', serving: '1 piece or cup', oxalateMg: 45.7, level: OxalateLevel.high, category: 'Mixed Dishes', tip: 'Watch out for meat lasagna and mac & cheese. Pizza in moderation is fine. Avoid high-oxalate pasta dishes.'),
  FoodItem(name: 'Pizza Restaurant & Frozen Cheese', serving: '2 slices', oxalateMg: 8.5, level: OxalateLevel.low, category: 'Mixed Dishes', tip: 'Watch out for meat lasagna and mac & cheese. Pizza in moderation is fine. Avoid high-oxalate pasta dishes.'),
  FoodItem(name: 'Almond Butter Salted', serving: '1 tbsp', oxalateMg: 41.6, level: OxalateLevel.high, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Almonds Oil Roasted', serving: '1 oz', oxalateMg: 72.0, level: OxalateLevel.veryHigh, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Cashews Oil Roasted', serving: '1 oz', oxalateMg: 63.5, level: OxalateLevel.veryHigh, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Coconut Meat Dried Sweetened Shredded', serving: '1 tbsp', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Coconut Meat Raw', serving: '1/8 cup', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Flaxseed Ground', serving: '1 tbsp', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Mixed Nuts With Peanuts Oil Roasted', serving: '1 oz', oxalateMg: 45.2, level: OxalateLevel.high, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Peanut Butter Salted Smooth', serving: '1 tbsp', oxalateMg: 19.2, level: OxalateLevel.moderate, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Peanuts Dry Roasted', serving: '1 oz', oxalateMg: 28.8, level: OxalateLevel.high, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Peanuts Oil Roasted Salted', serving: '1 oz', oxalateMg: 29.0, level: OxalateLevel.high, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Pecans Oil Roasted', serving: '1 oz', oxalateMg: 15.7, level: OxalateLevel.moderate, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Pistachios Dry Roasted', serving: '1 oz', oxalateMg: 9.0, level: OxalateLevel.low, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Pumpkin & Squash Seeds Whole Roasted', serving: '1/4 cup', oxalateMg: 4.3, level: OxalateLevel.low, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Pumpkin And Squash Seed Kernels Dried', serving: '1/4 cup', oxalateMg: 7.7, level: OxalateLevel.low, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Sesame Butter Tahini', serving: '1 tbsp', oxalateMg: 16.2, level: OxalateLevel.moderate, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Sunflower Seed Kernels Oil Roasted', serving: '1/4 cup', oxalateMg: 8.0, level: OxalateLevel.low, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Sunflower Seed Dried Kernels', serving: '1/4 cup', oxalateMg: 2.9, level: OxalateLevel.low, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Walnuts', serving: '1 oz', oxalateMg: 11.7, level: OxalateLevel.moderate, category: 'Nuts And Seeds', tip: nutsTip),
  FoodItem(name: 'Barley Cooked Pearled', serving: '1 cup', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Buckwheat Groats Roasted', serving: '1 cup', oxalateMg: 132.6, level: OxalateLevel.veryHigh, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Bulgur Cooked', serving: '1 cup', oxalateMg: 85.9, level: OxalateLevel.veryHigh, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Couscous Cooked', serving: '1 cup', oxalateMg: 15.1, level: OxalateLevel.moderate, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Oat Bran Raw', serving: '1/2 cup', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Quinoa Cooked', serving: '1 cup', oxalateMg: 54.4, level: OxalateLevel.veryHigh, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Rice Brown Cooked Long Grain', serving: '1 cup', oxalateMg: 18.7, level: OxalateLevel.moderate, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Rice White Cooked Long Grain', serving: '1 cup', oxalateMg: 3.8, level: OxalateLevel.low, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Spaghetti Cooked', serving: '1 cup', oxalateMg: 16.5, level: OxalateLevel.moderate, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Spaghetti Cooked Whole Wheat', serving: '1 cup', oxalateMg: 46.1, level: OxalateLevel.high, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Wheat Berries Cooked', serving: '1 cup', oxalateMg: 97.6, level: OxalateLevel.veryHigh, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Wheat Bran Crude', serving: '1 tbsp', oxalateMg: 7.5, level: OxalateLevel.low, category: 'Pasta And Grains', tip: grainsTip),
  FoodItem(name: 'Bacon Turkey Microwaved', serving: '2 slices', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Chicken Meat & Skin Roasted', serving: '3 oz', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Chicken Breast Deli Rotisserie', serving: '3 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Chicken Liver Simmered', serving: '1 oz', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Chicken Sausage', serving: 'one', oxalateMg: 1.8, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Chicken Thighs Wings And Legs', serving: '2 pieces', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Chicken Roasted Meat', serving: '3 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Turkey Breast Meat & Skin Roasted', serving: '3 oz', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Turkey Hot Dog', serving: 'one', oxalateMg: 2.5, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Turkey Meat Roasted', serving: '3 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Turkey Sausage Cooked', serving: 'one', oxalateMg: 3.5, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Turkey Cooked Ground', serving: '3 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Turkey Breast Meat Only Cooked Roasted', serving: '3 oz', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Poultry', tip: poultryTip),
  FoodItem(name: 'Mayonnaise', serving: '1 tbsp', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Mayonnaise Low Fat', serving: '1 tbsp', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Mayonnaise Olive Oil', serving: '1 tbsp', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Salad Dressing Creamy Ranch Fat Free', serving: '1.5 tbsp', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Salad Dressing Creamy Ranch Lite', serving: '1.5 tbsp', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Salad Dressing Creamy Ranch Regular', serving: '1.5 tbsp', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Salad Dressing Italian', serving: '1.5 tbsp', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Salad Dressing Italian Fat Free', serving: '1.5 tbsp', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Salad Dressing Italian Lite', serving: '1.5 tbsp', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Salad Dressing Italian Regular', serving: '1.5 tbsp', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Salad Dressing Olive Oil And Vinegar', serving: '1.5 tbsp', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Salad Dressings', tip: 'All salad dressings are very low oxalate. Use freely â€” they will not contribute to stone formation.'),
  FoodItem(name: 'Bars Energy', serving: 'one', oxalateMg: 10.6, level: OxalateLevel.moderate, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Bars High Protein', serving: 'one', oxalateMg: 20.1, level: OxalateLevel.low, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Corn Chips Tortilla', serving: '1 oz', oxalateMg: 7.1, level: OxalateLevel.low, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Jell-O Chocolate Pudding Snacks', serving: '1 snack cup', oxalateMg: 13.6, level: OxalateLevel.moderate, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Jell-O Vanilla Pudding Snacks', serving: '1 snack cup', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Jello Prepared From Packet', serving: '1/2 cup', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Popcorn Air Popped', serving: '3 cups', oxalateMg: 3.5, level: OxalateLevel.low, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Popcorn Ready To Eat & Microwave', serving: '3 cups', oxalateMg: 4.9, level: OxalateLevel.low, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Potato Chip/Tortilla Chip Combo', serving: '1 oz', oxalateMg: 11.8, level: OxalateLevel.moderate, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Potato Chips', serving: '1 oz', oxalateMg: 12.1, level: OxalateLevel.moderate, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Potato Chips Baked', serving: '1 oz', oxalateMg: 19.3, level: OxalateLevel.moderate, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Potato Chips Light', serving: '1 oz', oxalateMg: 12.2, level: OxalateLevel.moderate, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Pretzels Plain Hard Salted', serving: '1.5 oz', oxalateMg: 6.9, level: OxalateLevel.low, category: 'Snacks', tip: snacksTip),
  FoodItem(name: 'Chowder Clam Canned', serving: '1 cup', oxalateMg: 13.6, level: OxalateLevel.moderate, category: 'Soups And Chowder', tip: soupsTip),
  FoodItem(name: 'Soup Cream Of Mushroom Canned', serving: '1 cup', oxalateMg: 1.5, level: OxalateLevel.low, category: 'Soups And Chowder', tip: soupsTip),
  FoodItem(name: 'Soup Lentil', serving: '1/2 cup', oxalateMg: 16.8, level: OxalateLevel.moderate, category: 'Soups And Chowder', tip: soupsTip),
  FoodItem(name: 'Soup Miso', serving: '1 cup', oxalateMg: 58.3, level: OxalateLevel.veryHigh, category: 'Soups And Chowder', tip: soupsTip),
  FoodItem(name: 'Soup Tomato Canned', serving: '1 cup', oxalateMg: 9.0, level: OxalateLevel.low, category: 'Soups And Chowder', tip: soupsTip),
  FoodItem(name: 'Aspartame Equal Nutrasweet', serving: '1 packet', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Artificial Sweeteners', tip: 'All artificial sweeteners are zero oxalate. Use any of them freely as sugar substitutes.'),
  FoodItem(name: 'Saccharin', serving: '1 packet', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Artificial Sweeteners', tip: 'All artificial sweeteners are zero oxalate. Use any of them freely as sugar substitutes.'),
  FoodItem(name: 'Stevia', serving: '1 packet', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Artificial Sweeteners', tip: 'All artificial sweeteners are zero oxalate. Use any of them freely as sugar substitutes.'),
  FoodItem(name: 'Sucralose Splenda', serving: '1 packet', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Artificial Sweeteners', tip: 'All artificial sweeteners are zero oxalate. Use any of them freely as sugar substitutes.'),
  FoodItem(name: 'Truvia', serving: '1 packet', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Artificial Sweeteners', tip: 'All artificial sweeteners are zero oxalate. Use any of them freely as sugar substitutes.'),
  FoodItem(name: 'Jams And Preserves', serving: '1 tbsp', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Sugars', tip: 'Sugar, honey, maple syrup, and molasses are all very low oxalate. Use as sweeteners freely.'),
  FoodItem(name: 'Molasses', serving: '1 tbsp', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Sugars', tip: 'Sugar, honey, maple syrup, and molasses are all very low oxalate. Use as sweeteners freely.'),
  FoodItem(name: 'Sugar Granulated', serving: '1 tsp', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Sugars', tip: 'Sugar, honey, maple syrup, and molasses are all very low oxalate. Use as sweeteners freely.'),
  FoodItem(name: 'Syrup Pancake', serving: '1 tbsp', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Sugars', tip: 'Sugar, honey, maple syrup, and molasses are all very low oxalate. Use as sweeteners freely.'),
  FoodItem(name: 'Arugula Raw', serving: '1/2 cup', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Asparagus Boiled Drained', serving: '1/2 cup', oxalateMg: 8.7, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Winter Squash Baked Unsalted', serving: '1/2 cup', oxalateMg: 4.0, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Bamboo Shoots Canned Drained', serving: '1/2 cup', oxalateMg: 6.3, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Beets Canned Drained', serving: '1/2 cup', oxalateMg: 76.4, level: OxalateLevel.veryHigh, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Broccoli Boiled Drained', serving: '1/2 cup', oxalateMg: 6.0, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Brussels Sprouts Boiled Drained', serving: '1/2 cup', oxalateMg: 17.0, level: OxalateLevel.moderate, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Cabbage Boiled Drained', serving: '1/2 cup', oxalateMg: 1.4, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Carrots Boiled Drained', serving: '1/2 cup', oxalateMg: 8.2, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Carrots Raw', serving: '1/2 large', oxalateMg: 4.5, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Cauliflower Boiled Drained', serving: '1/2 cup', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Celery Raw', serving: '1/2 medium', oxalateMg: 7.6, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Coleslaw Fast Food', serving: '1/2 cup', oxalateMg: 2.4, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Collards Boiled Drained', serving: '1/2 cup', oxalateMg: 4.9, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Corn Kernels Sweet Yellow Boiled', serving: '1/2 cup', oxalateMg: 0.8, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Cucumber With Peel Raw', serving: '1/4 cuke', oxalateMg: 1.0, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Endive Raw', serving: '1 cup', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'French Fries Fast Food', serving: '6 oz', oxalateMg: 48.6, level: OxalateLevel.high, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'French Fries Sweet Potato', serving: '6 oz', oxalateMg: 37.1, level: OxalateLevel.high, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Frozen French Fries Prepared', serving: '6 oz', oxalateMg: 36.9, level: OxalateLevel.high, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Garlic Cooked', serving: '1 clove', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Garlic Powder', serving: '4 shakes', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Garlic Raw', serving: '1 clove', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Green Beans Boiled Drained', serving: '1/2 cup', oxalateMg: 13.6, level: OxalateLevel.moderate, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Kale Boiled Drained', serving: '1/2 cup', oxalateMg: 1.1, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Kale Raw', serving: '1 cup', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Lettuce Iceberg', serving: '1 cup', oxalateMg: 0.4, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Lettuce Romaine', serving: '1 cup', oxalateMg: 0.3, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Lima Beans Boiled Drained', serving: '1/2 cup', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Marinara/Spaghetti Sauce Ready To Serve', serving: '1/2 cup', oxalateMg: 10.4, level: OxalateLevel.moderate, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Mixed Frozen Vegetables Boiled Drained', serving: '1/2 cup', oxalateMg: 4.5, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Mushrooms White Raw', serving: 'one', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Mushrooms White Cooked Boiled Drained', serving: 'one', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Mustard Greens Boiled Drained', serving: '1/2 cup', oxalateMg: 1.9, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Onions Raw', serving: 'one', oxalateMg: 2.1, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Onions Spring Or Scallions Raw', serving: 'one', oxalateMg: 0.0, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Parsley Raw', serving: '1 tbsp', oxalateMg: 0.9, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Peas Green Boiled Drained', serving: '1/2 cup', oxalateMg: 0.5, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Peppers Green Hot Chili Canned', serving: '1 oz', oxalateMg: 2.0, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Peppers Green Raw', serving: '2 rings', oxalateMg: 2.2, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Peppers Red Raw', serving: '2 rings', oxalateMg: 2.2, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Pickles Cucumber Sweet', serving: 'one', oxalateMg: 1.0, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Potato Salad', serving: '1/3 cup', oxalateMg: 16.9, level: OxalateLevel.moderate, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Potato Baked Flesh & Skin', serving: 'one', oxalateMg: 91.7, level: OxalateLevel.veryHigh, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Potato Microwaved Skin & Flesh', serving: 'one', oxalateMg: 68.0, level: OxalateLevel.veryHigh, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Potato Instant & Home Mashed', serving: '1 cup', oxalateMg: 11.6, level: OxalateLevel.moderate, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Sweet Potato Cooked Baked In Skin', serving: '1/2 cup', oxalateMg: 54.2, level: OxalateLevel.veryHigh, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Sweet Potato Canned Drained With Syrup', serving: '1/2 cup', oxalateMg: 14.3, level: OxalateLevel.moderate, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Pumpkin Canned No Salt', serving: '1 cup', oxalateMg: 8.8, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Radishes Raw', serving: '2 radishes', oxalateMg: 0.1, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Salsa', serving: '1/4 cup', oxalateMg: 2.8, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Seaweed', serving: '1/2 cup', oxalateMg: 0.7, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Soybeans Green Boiled Drained', serving: '1/2 cup', oxalateMg: 48.0, level: OxalateLevel.high, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Spinach Boiled Drained', serving: '1/2 cup', oxalateMg: 547.4, level: OxalateLevel.veryHigh, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Spinach Raw', serving: '1 cup', oxalateMg: 316.2, level: OxalateLevel.veryHigh, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Squash Summer Boiled Drained', serving: '1/2 cup', oxalateMg: 0.6, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Tomato Products Canned Paste', serving: '1/4 cup', oxalateMg: 24.5, level: OxalateLevel.moderate, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Tomatoes Ripe Red', serving: '2 slices', oxalateMg: 3.1, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
  FoodItem(name: 'Waterchestnuts Chinese Canned', serving: '1/8 cup', oxalateMg: 0.2, level: OxalateLevel.low, category: 'Vegetables', tip: vegetablesTip),
];

// â”€â”€â”€ MAIN HOME PAGE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
